GAMES='11111 22222 33333'
LOG_FILE=18xx.games_notify.log
RESEND_TIME=14400

#IDs in square bracket must corespond with 18xx.games user id.

USER[123]="Test_name"
USEREMAIL[123]="email@gmail.com"
USERNICK[123]="Test_nick"
USERHO[123]="Hangouts_user_or_group_chat_ID ex: UgyORgW6YKfcH1J7blF4AaABAQ"

USER[456]="Test_name2"
USEREMAIL[456]="email2@gmail.com"
USERNICK[456]="Test_nick2"
USERHO[456]="Hangouts_user_or_group_chat_ID ex: UgyORgW6YKfcH1J7blF4AaABAQ"


